name: calc
channels:
  - conda-forge
dependencies:
  - python
  - dash
  - dash-bootstrap-components
  - plotly
  - pandas
  - numpy
  - us
  - pip
  - pip:
      - jupyter-book
<<<<<<< HEAD
      - us
      - numerize
      - kaleido
=======
>>>>>>> upstream/main
      - "git+https://github.com/PSLmodels/microdf"
