name: calc
channels:
  - conda-forge
dependencies:
  - python
  - us
  - dash
  - dash-bootstrap-components
  - plotly
  - "pandas>=1.2.3"
  - numpy
  - pip
  - pip:
      - jupyter-book
      - "git+https://github.com/PSLmodels/microdf"
